services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern
    depends_on:
      - mongo
  

  frontend:
    build: ./frontend

    ports:
      - "3000:3000"
    
    environment:
      - SKIP_PREFLIGHT_CHECK=true
    
    depends_on:
      - backend

  
  mongo:
    image: mongo:6

    ports:
      - "27017:27017"