name: Ecommerce Website CICD

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Code
              uses: actions/checkout@v4

            - name: Login To docker
              uses:  docker/login-action@v3
              with:
                username: ${{vars.DOCKER_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}
            
            - name: Build and Push Backend Image
              run: |
                docker build -t ${{vars.DOCKER_USERNAME}}/backend:latest ./backend
                docker push ${{vars.DOCKER_USERNAME}}/backend:latest
            
            - name: Build and Push  Frontend Image
              run: |
                docker build -t ${{vars.DOCKER_USERNAME}}/frontend:latest ./frontend
                docker push ${{vars.DOCKER_USERNAME}}/frontend:latest
    deploy:
        # This runs on ubuntu
        runs-on: ubuntu-latest
        # needs the build and push
        needs: build_and_push
        steps:
            - name: Connect using ssh
              uses: appleboy/ssh-action@master
              with:
                host: ${{secrets.EC2_HOST_SERVER}} 
                username: ${{secrets.EC2_USERNAME}}
                key: ${{secrets.EC2_PRIVATE_KEY}}
                script: |
                    cd /home/ubuntu/david
                    sudo docker login -u ${{vars.DOCKER_USERNAME}} -p ${{secrets.DOCKER_USERNAME}}
                    sudo docker-compose pull
                    sudo docker-compose down
                    sudo docker-compose up -d
                    # sudo docker run -d -p 3000:3000 --name ndubuisi ${{vars.DOCKER_USERNAME}}/frontend
